script:
  # clang build
  - make CXX=clang++-6.0 dft.o

  # gcc build with profiler
  - make CXX=g++-6 DEBUG='-g -pg -O3' clean dft.o
  - ./dft.o && gprof --brief ./dft.o

  # CPP check
  - make CXX=g++-6 clean all
  - cppcheck --enable=all .

  # Upload coverage
  - bash <(curl -s https://codecov.io/bash)

# Deploy to GitHub pages
deploy:
  provider: pages
  github-token: ${api_key}
  skip-cleanup: true
  on:
    branch: master

# Linux build with gcc and clang
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang++-6.0
            - g++-6
            - cppcheck
            - gnuplot
